# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_inspectr_wrappers", use_symbols = TRUE, package_name = "inspectr")

#' @docType package
#' @usage NULL
#' @useDynLib inspectr, .registration = TRUE
NULL

#' Inspect obj's representation using visualizr.
#' @export
visualize <- function(obj) invisible(.Call(wrap__visualize, obj))

